name: steam_watcher

environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6 # Para consumir a API Steam
  provider: ^6.0.5 # Para gerenciamento de estado
  shared_preferences: ^2.2.0 # Para armazenar configurações localmente
  firebase_messaging: ^14.7.6 # Para notificações push (opcional)

flutter:
  uses-material-design: true


